#!/usr/bin/env bash
# HomeOS — Samba baseline.
# The daemon config is split in two: this file owns [global], and everything
# under /etc/homeos/samba/shares.conf is generated by homeos-core (phase 2).
# That split means the storage API never has to parse or rewrite smb.conf.
# shellcheck shell=bash

[[ -n "${_HOMEOS_SAMBA_SH:-}" ]] && return 0
_HOMEOS_SAMBA_SH=1

samba::configure() {
    log::step "Samba (SMB file sharing)"

    ensure_dir /etc/homeos/samba 0755 root:root

    # Created empty so smbd starts cleanly before any share exists.
    if [[ ! -f /etc/homeos/samba/shares.conf ]]; then
        write_file /etc/homeos/samba/shares.conf 0644 root:root <<'CONF'
# Generated by homeos-core. Do not edit by hand: the storage manager rewrites
# this file whenever a share is created, modified or removed.
# Edit [global] settings in /etc/samba/smb.conf instead.
CONF
    else
        log::skip "managed share file exists"
    fi

    samba::write_global
    samba::apply
}

samba::write_global() {
    backup_file /etc/samba/smb.conf
    ensure_dir /etc/samba 0755 root:root

    write_file /etc/samba/smb.conf 0644 root:root <<CONF
#
# HomeOS-managed Samba configuration.
#
# [global] is owned by install.sh. Individual shares live in the included file
# below and are written by homeos-core; hand edits there will be overwritten.
#
[global]
   workgroup = WORKGROUP
   server string = ${HOMEOS_HOSTNAME} (HomeOS)
   netbios name = ${HOMEOS_HOSTNAME}
   server role = standalone server

   # SMB1 is off: it is unauthenticated-by-design and the source of most
   # historic SMB vulnerabilities. Modern clients all speak SMB2+.
   server min protocol = SMB2_10
   client min protocol = SMB2_10
   server smb encrypt = desired

   security = user
   map to guest = never
   guest account = nobody
   obey pam restrictions = yes
   unix password sync = no
   pam password change = no

   # Avahi already advertises the host; NetBIOS name service is legacy noise.
   disable netbios = yes
   dns proxy = no
   smb ports = 445

   # Performance: sendfile plus a larger socket buffer roughly doubles
   # sequential throughput on gigabit links.
   use sendfile = yes
   aio read size = 16384
   aio write size = 16384
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   strict allocate = yes

   # Bind only to real LAN interfaces; never to docker bridges.
   bind interfaces only = yes
   interfaces = lo ${HOMEOS_PRIMARY_IFACE}

   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d

   # Recycle bin semantics for every share, so a deleted holiday album is
   # recoverable instead of gone.
   vfs objects = recycle
   recycle:repository = .recycle/%U
   recycle:keeptree = yes
   recycle:versions = yes
   recycle:touch = no
   recycle:exclude = *.tmp, *.temp, *.o, *.obj, ~\$*
   recycle:exclude_dir = /tmp, /cache

   include = /etc/homeos/samba/shares.conf
CONF
}

samba::apply() {
    if have testparm; then
        if run_quiet testparm -s --suppress-prompt; then
            log::ok "smb.conf validates"
        else
            die "generated smb.conf failed validation - not restarting Samba"
        fi
    fi

    svc_enable_now smbd.service || log::warn "smbd did not start"

    # nmbd serves NetBIOS browsing, which we deliberately disabled above.
    if systemctl list-unit-files nmbd.service >/dev/null 2>&1; then
        run systemctl disable --now nmbd.service >/dev/null 2>&1 || true
        log::info "nmbd disabled (Avahi handles discovery)"
    fi
}
