// Package samba owns /etc/homeos/samba/shares.conf.
//
// Phase 1 split smb.conf in two: install.sh owns [global], and that file
// `include`s this one. So the daemon never parses or rewrites smb.conf -- it
// regenerates one file it fully controls and asks smbd to reload. An operator
// editing [global] and HomeOS adding a share cannot clobber each other.
package samba

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
	"sync"
)

type Share struct {
	Name     string `json:"name"`
	Path     string `json:"path"`
	Comment  string `json:"comment,omitempty"`
	ReadOnly bool   `json:"read_only"`
	// Public exposes the share without authentication. Off by default; the API
	// requires it to be set explicitly rather than inferring it from an empty
	// user list, so nobody publishes their files by forgetting a field.
	Public bool `json:"public"`
	// ValidUsers restricts access when the share is not public.
	ValidUsers []string `json:"valid_users,omitempty"`
	// Browseable controls visibility in network browsers, not access.
	Browseable  bool `json:"browseable"`
	RecycleBin  bool `json:"recycle_bin"`
	TimeMachine bool `json:"time_machine,omitempty"`
}

// shareNameRE also guards against a name that would break out of its section
// header and inject directives into the generated file.
var shareNameRE = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,31}$`)

var userNameRE = regexp.MustCompile(`^[a-z_][a-z0-9_-]{0,31}$`)

func (s Share) Validate(allowedRoots []string) error {
	if !shareNameRE.MatchString(s.Name) {
		return fmt.Errorf("share name %q must be 1-32 chars of letters, digits, dot, dash or underscore", s.Name)
	}
	if s.Path == "" || !strings.HasPrefix(s.Path, "/") || path.Clean(s.Path) != s.Path {
		return fmt.Errorf("share path %q must be an absolute, normalised path", s.Path)
	}
	// Confine shares to the roots HomeOS manages, so a share cannot export /etc.
	ok := false
	for _, root := range allowedRoots {
		if s.Path == root || strings.HasPrefix(s.Path, strings.TrimSuffix(root, "/")+"/") {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("share path %q must be under one of %s", s.Path, strings.Join(allowedRoots, ", "))
	}
	if strings.ContainsAny(s.Comment, "\n\r[]") {
		return fmt.Errorf("share comment must not contain newlines or brackets")
	}
	for _, u := range s.ValidUsers {
		if !userNameRE.MatchString(u) {
			return fmt.Errorf("invalid user name %q", u)
		}
	}
	if !s.Public && len(s.ValidUsers) == 0 {
		return fmt.Errorf("share %q is not public and lists no users, so nobody could reach it", s.Name)
	}
	return nil
}

// Render produces the complete managed share file. Pure, so the exact output is
// tested rather than inferred.
func Render(shares []Share, shareGroup string) []byte {
	sorted := append([]Share(nil), shares...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b bytes.Buffer
	b.WriteString("# Generated by homeos-core. Do not edit by hand.\n")
	b.WriteString("# The storage manager rewrites this file whenever a share changes.\n")
	b.WriteString("# Global settings live in /etc/samba/smb.conf.\n")

	for _, s := range sorted {
		fmt.Fprintf(&b, "\n[%s]\n", s.Name)
		if s.Comment != "" {
			fmt.Fprintf(&b, "   comment = %s\n", s.Comment)
		}
		fmt.Fprintf(&b, "   path = %s\n", s.Path)
		fmt.Fprintf(&b, "   browseable = %s\n", yesno(s.Browseable))
		fmt.Fprintf(&b, "   read only = %s\n", yesno(s.ReadOnly))

		if s.Public {
			b.WriteString("   guest ok = yes\n")
			b.WriteString("   public = yes\n")
		} else {
			b.WriteString("   guest ok = no\n")
			if len(s.ValidUsers) > 0 {
				users := append([]string(nil), s.ValidUsers...)
				sort.Strings(users)
				fmt.Fprintf(&b, "   valid users = %s\n", strings.Join(users, " "))
			}
		}

		if !s.ReadOnly {
			// New files inherit the share group so other HomeOS users and the
			// app containers can reach what was written over SMB.
			fmt.Fprintf(&b, "   force group = %s\n", shareGroup)
			b.WriteString("   create mask = 0664\n")
			b.WriteString("   directory mask = 0775\n")
			b.WriteString("   force create mode = 0660\n")
			b.WriteString("   force directory mode = 0770\n")
		}

		// [global] turns the recycle VFS on for everything; a share that opts
		// out has to disable it explicitly.
		if !s.RecycleBin {
			b.WriteString("   vfs objects =\n")
		}

		if s.TimeMachine {
			// Time Machine needs the fruit stack and an advertised quota;
			// without vfs_fruit macOS refuses to use the share as a target.
			b.WriteString("   vfs objects = catia fruit streams_xattr\n")
			b.WriteString("   fruit:time machine = yes\n")
			b.WriteString("   fruit:metadata = stream\n")
			b.WriteString("   ea support = yes\n")
		}
	}
	return b.Bytes()
}

func yesno(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// Manager writes the file and reloads smbd.
type Manager struct {
	configPath   string
	shareGroup   string
	allowedRoots []string
	log          *slog.Logger
	run          func(ctx context.Context, name string, args ...string) ([]byte, error)
	mu           sync.Mutex
}

func NewManager(configPath, shareGroup string, allowedRoots []string, log *slog.Logger,
	run func(context.Context, string, ...string) ([]byte, error)) *Manager {
	return &Manager{
		configPath:   configPath,
		shareGroup:   shareGroup,
		allowedRoots: allowedRoots,
		log:          log,
		run:          run,
	}
}

// Apply validates, writes and reloads. It writes via a temp file and rename so
// smbd can never observe a half-written config.
func (m *Manager) Apply(ctx context.Context, shares []Share) error {
	seen := map[string]bool{}
	for _, s := range shares {
		if err := s.Validate(m.allowedRoots); err != nil {
			return err
		}
		if seen[strings.ToLower(s.Name)] {
			return fmt.Errorf("duplicate share name %q", s.Name)
		}
		seen[strings.ToLower(s.Name)] = true
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	rendered := Render(shares, m.shareGroup)
	tmp := m.configPath + ".homeos-tmp"
	if err := os.WriteFile(tmp, rendered, 0o644); err != nil {
		return fmt.Errorf("stage share config: %w", err)
	}

	// testparm against the staged file would need it in place, so validation
	// happens after the rename and rolls back on failure.
	prev, _ := os.ReadFile(m.configPath)
	if err := os.Rename(tmp, m.configPath); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("replace share config: %w", err)
	}

	if _, err := m.run(ctx, "testparm", "-s", "--suppress-prompt"); err != nil {
		if prev != nil {
			_ = os.WriteFile(m.configPath, prev, 0o644)
		}
		return fmt.Errorf("generated Samba config is invalid, rolled back: %w", err)
	}

	if _, err := m.run(ctx, "smbcontrol", "all", "reload-config"); err != nil {
		m.log.Warn("samba reload failed; config written", "error", err)
	}
	m.log.Info("samba shares applied", "count", len(shares))
	return nil
}
